version: 2
jobs:
  build:
    working_directory: ~/redprint
    docker:
      - image: circleci/node:8.4.0
    steps:
      # Copy source
      - checkout

      # Install Dependencies
      - restore_cache:
          key: redprint-dependencies-{{ checksum "package.json" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: redprint-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn

      # Test
      - run:
          name: Test
          command: yarn test
      - run:
          name: Coverage report
          command: bash <(curl -s https://codecov.io/bash)